package router


import (
	"database/sql"

	"github.com/gin-gonic/gin"

	"github.com/guish/university-social/internal/config"
	"github.com/guish/university-social/internal/handler"
	"github.com/guish/university-social/internal/middleware"
	"github.com/guish/university-social/internal/repository"
	"github.com/guish/university-social/internal/cache"
)

func Setup(db *sql.DB, cfg *config.Config, rdb *cache.Cache) *gin.Engine {
	userRepo := repository.NewUserRepository(db)
	postRepo := repository.NewPostRepository(db)
	sensitiveRepo := repository.NewSensitiveWordRepository(db)
	pointsRepo := repository.NewPointsRepository(db)
	postHandler := handler.NewPostHandler(postRepo, sensitiveRepo, pointsRepo)
	authHandler := handler.NewAuthHandler(userRepo, cfg, pointsRepo)
	friendRepo := repository.NewFriendRepository(db)
	friendHandler := handler.NewFriendHandler(friendRepo)
	circleRepo := repository.NewCircleRepository(db)
	circleHandler := handler.NewCircleHandler(circleRepo)
	adminHandler := handler.NewAdminHandler(db)
	uploadHandler := handler.NewUploadHandler(cfg.UploadDir)
	whisperRepo := repository.NewWhisperRepository(db)
	whisperHandler := handler.NewWhisperHandler(whisperRepo, sensitiveRepo)
	reportRepo := repository.NewReportRepository(db)
	reportHandler := handler.NewReportHandler(reportRepo)
	sensitiveHandler := handler.NewSensitiveHandler(sensitiveRepo)

	productRepo := repository.NewProductRepository(db)
	productHandler := handler.NewProductHandler(productRepo)

	inviteRepo := repository.NewInviteCodeRepository(db)
	inviteHandler := handler.NewInviteCodeHandler(inviteRepo, userRepo, pointsRepo)

	verifRepo := repository.NewVerificationRepository(db)
	verifHandler := handler.NewVerificationHandler(verifRepo, cfg)
	followRepo := repository.NewFollowRepository(db)
	followHandler := handler.NewFollowHandler(followRepo, friendRepo)

	activityRepo := repository.NewActivityRepository(db)
	activityHandler := handler.NewActivityHandler(activityRepo)
	pointsHandler := handler.NewPointsHandler(pointsRepo)

	courseRepo := repository.NewCourseRepository(db)
	courseHandler := handler.NewCourseHandler(courseRepo)

	lostItemRepo := repository.NewLostItemRepository(db)
	lostItemHandler := handler.NewLostItemHandler(lostItemRepo)
	bannerRepo := repository.NewBannerRepository(db)
	bannerHandler := handler.NewBannerHandler(bannerRepo, rdb)
	msgRepo := repository.NewMessageRepository(db)
	chatHandler := handler.NewChatHandler(msgRepo)
	wsHub := handler.NewWsHub(msgRepo)
	campusRepo := repository.NewCampusRepository(db)
	campusHandler := handler.NewCampusHandler(campusRepo)
blockRepo := repository.NewBlockRepository(db)
blockHandler := handler.NewBlockHandler(blockRepo)



	r := gin.Default()
	r.Use(middleware.CORS())
	r.Static("/uploads", cfg.UploadDir)

	api := r.Group("/api/v1")

	api.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "ok"})
	})
	{
		api.POST("/auth/login", authHandler.WxLogin)
		api.POST("/auth/dev-login", authHandler.DevLogin)

		auth := api.Group("")
		auth.Use(middleware.AuthRequired(cfg))
		{
			auth.GET("/user/profile", authHandler.GetProfile)
			auth.PUT("/user/profile", authHandler.UpdateProfile)
			auth.GET("/users/:id", authHandler.GetUser)
			auth.POST("/posts", postHandler.CreatePost)
			auth.GET("/posts", postHandler.ListPosts)
			auth.GET("/posts/:id", postHandler.GetPost)
			auth.PUT("/posts/:id", postHandler.UpdatePost)
			auth.DELETE("/posts/:id", postHandler.DeletePost)
			auth.POST("/posts/:id/comments", postHandler.CreateComment)
			auth.GET("/posts/:id/comments", postHandler.ListComments)
			auth.POST("/posts/:id/like", postHandler.ToggleLike)
			auth.GET("/topics", postHandler.ListTopics)
			auth.GET("/posts/:id/share", postHandler.ShareCard)
			auth.GET("/users/search", friendHandler.SearchUsers)
			auth.GET("/friends", friendHandler.ListFriends)
			auth.GET("/friends/requests", friendHandler.ListRequests)
			auth.POST("/friends/request/:id", friendHandler.SendRequest)
			auth.POST("/friends/accept/:id", friendHandler.AcceptRequest)
			auth.DELETE("/friends/:id", friendHandler.RemoveFriend)
			auth.POST("/friends/reject/:id", friendHandler.RejectRequest)
			auth.GET("/notifications", friendHandler.ListNotifications)
			auth.POST("/notifications/read", friendHandler.MarkRead)
			auth.GET("/circles", circleHandler.List)
			auth.POST("/circles", circleHandler.Create)
			auth.GET("/circles/:id", circleHandler.GetByID)
			auth.PUT("/circles/:id", circleHandler.Update)
			auth.POST("/circles/:id/join", circleHandler.Join)
			auth.POST("/circles/:id/leave", circleHandler.Leave)
			auth.GET("/circles/:id/members", circleHandler.ListMembers)
			auth.GET("/circles/:id/posts", circleHandler.ListPosts)
			auth.POST("/circles/:id/posts", circleHandler.CreatePost)
			auth.POST("/circles/posts/:pid/like", circleHandler.TogglePostLike)
			auth.POST("/circles/posts/:pid/comments", circleHandler.CreateComment)
			auth.GET("/circles/posts/:pid/comments", circleHandler.ListComments)
			auth.POST("/upload", uploadHandler.UploadImage)
			auth.GET("/circles/:id/join-requests", circleHandler.ListJoinRequests)
			auth.POST("/circles/join-requests/:requestId/handle", circleHandler.HandleJoinRequest)
			auth.GET("/circles/:id/avatar-wall", circleHandler.MemberAvatarWall)
		auth.GET("/circles/:id/activities", circleHandler.ListActivities)
			auth.GET("/whispers", whisperHandler.List)
			auth.POST("/whispers", whisperHandler.Create)
			auth.GET("/whispers/:id", whisperHandler.Get)
			auth.DELETE("/whispers/:id", whisperHandler.Delete)
			auth.POST("/whispers/:id/like", whisperHandler.ToggleLike)
			auth.POST("/whispers/:id/comments", whisperHandler.CreateComment)
			auth.GET("/whispers/:id/comments", whisperHandler.ListComments)
			auth.GET("/whispers/summary", whisperHandler.Summary)
			auth.POST("/invite-codes", inviteHandler.Create)
			auth.GET("/invite-codes", inviteHandler.MyCodes)
			auth.POST("/invite-codes/redeem", inviteHandler.Redeem)
			auth.POST("/verification/send-code", verifHandler.SendCode)
			auth.POST("/verification/verify", verifHandler.Verify)
			auth.GET("/verification/status", verifHandler.Status)
			auth.POST("/follow/:id", followHandler.Follow)
			auth.DELETE("/follow/:id", followHandler.Unfollow)
			auth.GET("/banners", bannerHandler.ListActive)
			auth.GET("/announcements", bannerHandler.ListAnnouncementsActive)
			auth.GET("/posts/featured", bannerHandler.ListFeatured)
			auth.GET("/follow/:id/check", followHandler.IsFollowing)
			auth.GET("/users/:id/following", followHandler.Following)
			auth.GET("/users/:id/followers", followHandler.Followers)
			auth.GET("/users/:id/follow-counts", followHandler.Counts)
			auth.GET("/posts/search", postHandler.SearchPosts)
			auth.GET("/posts/trending", postHandler.TrendingPosts)
			auth.GET("/circles/search", circleHandler.SearchCircles)
			auth.GET("/posts/following", postHandler.FollowingPosts)
			auth.GET("/users/:id/posts", postHandler.UserPosts)
			auth.POST("/products", productHandler.Create)
			auth.GET("/products", productHandler.List)
			auth.GET("/products/categories", productHandler.Categories)
			auth.GET("/products/trending", productHandler.Trending)
			auth.GET("/products/search", productHandler.Search)
			auth.GET("/products/:id", productHandler.GetByID)
			auth.DELETE("/products/:id", productHandler.Delete)
			auth.PUT("/products/:id/sold", productHandler.MarkSold)
			auth.POST("/products/:id/like", productHandler.ToggleLike)
			auth.GET("/products/my", productHandler.MyProducts)
			auth.POST("/products/:id/comments", productHandler.CreateComment)
			auth.GET("/products/:id/comments", productHandler.ListComments)

			auth.GET("/activities", activityHandler.List)
			auth.POST("/activities", activityHandler.Create)
			auth.GET("/activities/types", activityHandler.Types)
			auth.GET("/activities/my", activityHandler.MyActivities)
			auth.GET("/activities/:id", activityHandler.GetByID)
			auth.DELETE("/activities/:id", activityHandler.Delete)
			auth.POST("/activities/:id/join", activityHandler.Join)
			auth.POST("/activities/:id/leave", activityHandler.Leave)
			auth.GET("/activities/:id/participants", activityHandler.Participants)
			auth.POST("/activities/:id/comments", activityHandler.CreateComment)
			auth.GET("/activities/:id/comments", activityHandler.ListComments)
			auth.POST("/reports", reportHandler.Create)
			auth.GET("/points/balance", pointsHandler.GetBalance)
			auth.POST("/points/daily-login", pointsHandler.ClaimDailyLogin)
			auth.GET("/points/logs", pointsHandler.GetLogs)
			auth.GET("/points/leaderboard", pointsHandler.GetLeaderboard)
			auth.GET("/courses/search", courseHandler.SearchCourses)
			auth.GET("/courses/:id", courseHandler.GetCourseDetail)
			auth.POST("/courses/:id/rating", courseHandler.CreateRating)
			auth.GET("/courses/:id/ratings", courseHandler.ListRatings)
			auth.GET("/courses/:id/my-rating", courseHandler.GetUserRating)
			auth.POST("/courses/rating/:ratingId/helpful", courseHandler.MarkHelpful)

			auth.GET("/lost-items", lostItemHandler.List)
			auth.POST("/lost-items", lostItemHandler.Create)
			auth.GET("/lost-items/my", lostItemHandler.MyItems)
			auth.GET("/lost-items/search", lostItemHandler.Search)
			auth.GET("/lost-items/:id", lostItemHandler.GetByID)
			auth.DELETE("/lost-items/:id", lostItemHandler.Delete)
			auth.PUT("/lost-items/:id/status", lostItemHandler.UpdateStatus)

			auth.GET("/ws", func(c *gin.Context) {
				handler.WsHandler(wsHub)(c)
			})
			auth.POST("/chat/send", chatHandler.Send)
			auth.GET("/chat/conversations", chatHandler.Conversations)
			auth.GET("/chat/messages/:userId", chatHandler.Messages)
			auth.POST("/chat/read/:userId", chatHandler.MarkRead)
			auth.GET("/chat/unread", chatHandler.UnreadCount)
			auth.GET("/campus/calendar", campusHandler.ListCalendar)
			auth.GET("/campus/directory", campusHandler.ListDirectory)
			auth.GET("/campus/rooms", campusHandler.ListEmptyRooms)
			auth.GET("/campus/rooms/buildings", campusHandler.ListBuildings)
			auth.POST("/users/:id/block", blockHandler.Block)
			auth.DELETE("/users/:id/block", blockHandler.Unblock)
			auth.GET("/users/:id/block-status", blockHandler.BlockStatus)
			auth.GET("/users/blocked", blockHandler.ListBlocked)

		}
		admin := api.Group("/admin")
		admin.Use(middleware.AuthRequired(cfg))
		admin.Use(middleware.AdminRequired(cfg))
		{
			admin.GET("/dashboard", adminHandler.Dashboard)
			admin.GET("/users", adminHandler.ListUsers)
			admin.PUT("/users/:id/ban", adminHandler.BanUser)
			admin.PUT("/users/:id/unban", adminHandler.UnbanUser)
			admin.GET("/posts", adminHandler.ListPosts)
			admin.DELETE("/posts/:id", adminHandler.DeletePost)
			admin.GET("/circles", adminHandler.ListCircles)
			admin.DELETE("/circles/:id", adminHandler.DeleteCircle)
			admin.GET("/reports", reportHandler.List)
			admin.PUT("/reports/:id/resolve", reportHandler.Resolve)
			admin.PUT("/reports/:id/dismiss", reportHandler.Dismiss)
			admin.GET("/sensitive-words", sensitiveHandler.List)
			admin.POST("/sensitive-words", sensitiveHandler.Add)
			admin.GET("/banners", bannerHandler.AdminList)
			admin.POST("/banners", bannerHandler.Create)
			admin.DELETE("/banners/:id", bannerHandler.Delete)
			admin.PUT("/banners/:id/toggle", bannerHandler.ToggleActive)
			admin.GET("/announcements", bannerHandler.AdminListAnnouncements)
			admin.POST("/announcements", bannerHandler.CreateAnnouncement)
			admin.DELETE("/announcements/:id", bannerHandler.DeleteAnnouncement)
			admin.PUT("/announcements/:id/toggle", bannerHandler.ToggleAnnouncementActive)
			admin.POST("/posts/:id/feature", bannerHandler.SetFeatured)
			admin.POST("/posts/:id/unfeature", bannerHandler.UnsetFeatured)
			admin.DELETE("/sensitive-words/:word", sensitiveHandler.Remove)
			admin.GET("/stats/daily", adminHandler.DailyStats)
			admin.GET("/operation-logs", adminHandler.ListLogs)
		}
	}

	return r
}
